// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vkbRUBvwUpq_Z-Y5kmMJAkHCsJS28h4',
    appId: '1:629140384888:web:f35165c7c2cc480da1118d',
    messagingSenderId: '629140384888',
    projectId: 'minimalchatapp-2c220',
    authDomain: 'minimalchatapp-2c220.firebaseapp.com',
    storageBucket: 'minimalchatapp-2c220.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGdOJc7dyjAudhGRiSJG5pR5yMM-wedsU',
    appId: '1:629140384888:android:cc436829485fdaaca1118d',
    messagingSenderId: '629140384888',
    projectId: 'minimalchatapp-2c220',
    storageBucket: 'minimalchatapp-2c220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7QVQiU9rZviyuP-kxnxO09Ywc6k604IQ',
    appId: '1:629140384888:ios:104b3130973fec4fa1118d',
    messagingSenderId: '629140384888',
    projectId: 'minimalchatapp-2c220',
    storageBucket: 'minimalchatapp-2c220.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7QVQiU9rZviyuP-kxnxO09Ywc6k604IQ',
    appId: '1:629140384888:ios:104b3130973fec4fa1118d',
    messagingSenderId: '629140384888',
    projectId: 'minimalchatapp-2c220',
    storageBucket: 'minimalchatapp-2c220.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vkbRUBvwUpq_Z-Y5kmMJAkHCsJS28h4',
    appId: '1:629140384888:web:c009efdb7d0e4c15a1118d',
    messagingSenderId: '629140384888',
    projectId: 'minimalchatapp-2c220',
    authDomain: 'minimalchatapp-2c220.firebaseapp.com',
    storageBucket: 'minimalchatapp-2c220.firebasestorage.app',
  );
}
